name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Revisar calidad del código con Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install flake8

      - name: Revisar código con Flake8
        run: flake8 lambda1 lambda2 --max-line-length=100

  test:
    name: Ejecutar pruebas unitarias con Pytest
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install -r lambda1/requirements.txt
          pip install pytest moto boto3

      - name: Ejecutar pruebas con Pytest
        run: pytest lambda1/tests

  deploy:
    name: Desplegar en AWS con Zappa
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install -r lambda1/requirements.txt
          pip install zappa

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Desplegar con Zappa
        run: |
          cd lambda1
          zappa update scrapping
          zappa invoke scrapping "lambda_function.lambda_handler"